apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color-r
  labels:
    app: web
spec:
  containers:
  - image: mmumshad/simple-webapp-color
    name: web
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: red
